routes/web.php
<?php
/**
 * Laravel Router
 */
Route::group(['prefix' => 'auth', 'namespace' => 'Auth'], function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::post('logout', 'LoginController@logout')->name('logout');
    Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'RegisterController@register');
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset');
    Route::get('socialite/{provider}', 'AuthController@redirectToProvider');
    Route::get('socialite/{provider}/callback', 'AuthController@handleProviderCallback');
});
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'roles'], 'block' => ['User']], function () {
    Route::group(['roles' => ['Author', 'Moderator', 'Admin']], function () {
        Route::get('/', 'AdminController@index')->name('admin.index');
    });
    Route::group(['roles' => ['Moderator', 'Admin']], function () {
        Route::resource('pages', 'PageController');
        Route::resource('social-link', 'SociallinkController');
        Route::resource('subscribes', 'SubscribeController');
        Route::resource('articles', 'ArticleController');
        Route::resource('categories', 'CategoryController');
        Route::resource('comments', 'CommentsController');
    });
    Route::group(['roles' => ['Admin']], function () {
        Route::resource('users', 'UserController');
        Route::get('roles', 'RoleController@index')->name('roles.index');
        Route::get('role/{id}', 'RoleController@show')->name('roles.show');
        Route::get('roles/{id}/edit', 'RoleController@edit')->name('roles.edit');
        Route::put('roles/{id}', 'RoleController@update')->name('roles.update');
        Route::resource('seo', 'SeoController');
        Route::get('settings', 'SettingController@index')->name('settings.index');
        Route::put('settings', 'SettingController@update')->name('settings.update');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('admin.logs');
    });
});
Route::namespace('Site')->group(function () {
    Route::get('/', 'SiteController@index')->name('site.index');
    Route::get('blog', 'ArticleController@index')->name('site.article.index');
    Route::get('blog/{url}', 'ArticleController@view')->name('site.article.view')->where('url', '[\w\d\-\_]+');
    Route::get('categories/{url}', 'CategoryController@view')->name('site.categories')->where('url', '[\w\d\-\_]+');

    Route::get('styles', 'SiteController@styles')->name('site.styles');
    Route::get('about', 'SiteController@about')->name('site.about');
    Route::get('contact', 'ContactController@contact')->name('site.contact');
    Route::post('contact', 'ContactController@submit');
    Route::get('privacy-policy', 'SiteController@privacypolicy')->name('site.privacy-policy');

    Route::post('comments/{id}', 'CommentsController@comments')->name('site.comments')->where('id', '[\w\d\-\_]+');
    Route::post('subscribe', 'SubscribeController@subscribe')->name('site.subscribe');
    Route::get('search', 'SearchController@search')->name('site.search');
    Route::middleware('auth')->group(function () {
        Route::get('profile', 'ProfileController@index')->name('profile.index');
        Route::get('profile/{id}/edit', 'ProfileController@edit')->name('profile.edit');
        Route::put('profile/{id}/edit', 'ProfileController@updateedit');
        Route::get('profile/{id}/password', 'ProfileController@password')->name('profile.password');
        Route::put('profile/{id}/password', 'ProfileController@updatepassword');
        Route::delete('profile/{id}', 'ProfileController@destroy')->name('profile.destroy');
    });
    Route::get('sitemap.xml', 'SitemapController@index')->name('sitemap.index');
    Route::get('sitemap/pages.xml', 'SitemapController@pages')->name('sitemap.pages');
    Route::get('sitemap/articles.xml', 'SitemapController@articles')->name('sitemap.articles');
    Route::get('sitemap/categories.xml', 'SitemapController@categories')->name('sitemap.categories');
});

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    /**
     * @var array
     */
    protected $fillable = ['title', 'url', 'images', 'text', 'category_id', 'seo_id', 'views', 'slide', 'status', 'user_id'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function seo()
    {
        return $this->belongsTo('App\Seo');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Article;
use App\Http\Controllers\Controller;
use App\Category;
use App\Seo;
use App\Http\Requests\Article as Request;
use App\User;
use Illuminate\Support\Facades\Auth;


class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $main = Article::all();
        return view('admin.articles.index', compact('main'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $seo = Seo::where('status', 1)->get();
        $categories = Category::where('status', 1)->get();
        return view('admin.articles.create', compact('seo', 'categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Article::create([
            'title' => $request->title,
            'url' => $request->url,
            'images' => $request->file('images')->store('articles', 'public'),
            'text' => $request->text,
            'category_id' => $request->category_id,
            'seo_id' => $request->seo_id,
            'views' => $request->views,
            'slide' => $request->slide,
            'status' => $request->status,
            'user_id' => Auth::user()->id,
        ]);
        return redirect()->route('articles.index')->with('success', __('admin.created-success'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $main = Article::find($id);
        return view('admin.articles.show', compact('main'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $main = Article::find($id);
        $seo = Seo::where('status', 1)->get();
        $categories = Category::where('status', 1)->get();
        $users = User::all();
        return view('admin.articles.edit', compact('main', 'categories', 'seo', 'users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Article::find($id)->update([
            'title' => $request->title,
            'url' => $request->url,
            'images' => $request->file('images')->store('articles', 'public'),
            'text' => $request->text,
            'category_id' => $request->category_id,
            'seo_id' => $request->seo_id,
            'views' => $request->views,
            'slide' => $request->slide,
            'status' => $request->status,
            'user_id' => $request->user_id
        ]);
        return redirect()->route('articles.index')->with('success', __('admin.updated-success'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Article::find($id)->delete();
        return redirect()->route('articles.index')->with('success', __('admin.information-deleted'));
    }
}

app/Http/Controllers/Site/ArticleController.php
<?php

namespace App\Http\Controllers\Site;

use App\Http\Controllers\Controller;
use App\Article;
use App\Comment;
use App\Page;
use App\Setting;

class ArticleController extends Controller
{

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $main = Page::find(2);
        $paginate = Setting::find(1)->paginate;
        $articles = Article::where('status', 1)->orderBy('id', 'desc')->paginate($paginate);
        return view('site.articles.index', compact('main', 'articles'));
    }

    /**
     * @param $url
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function view($url)
    {
        $main = Article::where('url', $url)->first();
        if (isset($main)) {
            $main->increment('views');
            $previous = Article::where('id', '<', $main->id)->orderBy('id', 'desc')->first();
            $next = Article::where('id', '>', $main->id)->orderBy('id')->first();
            $comments = Comment::where('status', 1)->where('article_id', $main->id)->get();
            $count = $comments->count();
            return view('site.articles.view', compact('main', 'previous', 'next', 'comments', 'count'));
        } else
        {
            abort(404);
        }
    }
}

resources/views/admin/articles/create.blade.php
@extends('admin.layouts.main')

@section('title',__('admin.create-articles'))

@section('content')
    @include('admin.includes.title')
    @include('admin.includes.error')
    <form action="{{ route('categories.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label>{{ __('admin.articles-name') }}</label>
            <input type="text" class="form-control" name="title"
                   placeholder="{{ __('admin.articles-enter-name') }}" required>
        </div>

        <div class="form-group">
            <label>{{ __('admin.articles-url') }}</label>
            <input type="text" class="form-control" name="url"
                   placeholder="{{ __('admin.articles-enter-url') }}" required>
        </div>

        <label>{{ __('admin.articles-images') }}</label><br>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text">{{ __('admin.articles-upload') }}</span>
            </div>
            <div class="custom-file">
                <input type="file" class="custom-file-input" name="images">
                <label class="custom-file-label"></label>
            </div>
        </div>

        <div class="form-group">
            <label>{{ __('admin.articles-text') }}</label>
            <textarea name="text" class="form-control" cols="30" placeholder="{{ __('admin.articles-enter-text') }}"
                      rows="10"></textarea>
        </div>

        <div class="form-group">
            <label>{{ __('admin.articles-category') }}</label>
            <select class="form-control" name="category_id" required>
                @foreach($categories as $item)
                    <option value="{{ $item->id }}">{{ $item->name.' ('.$item->id.')' }}</option>
                @endforeach
            </select>
        </div>


        <div class="form-group">
            <label>{{ __('admin.articles-seo') }}</label>
            <select class="form-control" name="seo_id" required>
                @foreach($seo as $item)
                    <option value="{{ $item->id }}">{{ $item->title.' ('.$item->id.')' }}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label>{{ __('admin.articles-views') }}</label>
            <input type="text" class="form-control" name="views"
                   placeholder="{{ __('admin.articles-enter-views') }}" required>
        </div>

        <div class="form-group">
            <label>{{ __('admin.articles-slide') }}</label>
            <select class="form-control" name="slide" required>
                <option value="1">{{ __('admin.enabled') }}</option>
                <option value="0">{{ __('admin.disabled') }}</option>
            </select>
        </div>

        <div class="form-group">
            <label>{{ __('admin.status') }}</label>
            <select class="form-control" name="status" required>
                <option value="1">{{ __('admin.enabled') }}</option>
                <option value="0">{{ __('admin.disabled') }}</option>
            </select>
        </div>

        <button class="btn btn-lg btn-original btn-block" type="submit">{{ __('admin.create') }}</button>
    </form>
@endsection

resources/views/admin/articles/edit.blade.php
@extends('admin.layouts.main')

@section('title',__('admin.edit-articles'))

@section('content')
    @include('admin.includes.title')
    @include('admin.includes.error')
    <form action="{{ route('articles.update',$main->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label>{{ __('admin.articles-name') }}</label>
            <input type="text" class="form-control" name="title" value="{{ $main->title }}"
                   placeholder="{{ __('admin.articles-enter-name') }}" required>
        </div>

        <div class="form-group">
            <label>{{ __('admin.articles-url') }}</label>
            <input type="text" class="form-control" name="url" value="{{ $main->url }}"
                   placeholder="{{ __('admin.articles-enter-url') }}" required>
        </div>

        <label>{{ __('admin.articles-images') }}</label><br>
        <img src="{{ asset('storage/'.$main->images) }}" width="300px" class="mb-3">
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text">{{ __('admin.articles-upload') }}</span>
            </div>
            <div class="custom-file">
                <input type="file" class="custom-file-input" name="images" value="{{ $main->images }}">
                <label class="custom-file-label">{{ $main->images }}</label>
            </div>
        </div>

        <div class="form-group">
            <label>{{ __('admin.articles-text') }}</label>
            <textarea name="text" class="form-control" cols="30" placeholder="{{ __('admin.articles-enter-text') }}" rows="10">{{ $main->text }}</textarea>
        </div>

        <div class="form-group">
            <label>{{ __('admin.articles-category') }}</label>
            <select class="form-control" name="category_id" required>
                <option value="{{ $main->category->id }}">{{ $main->category->name.' ('.$main->seo->id.')' }}</option>
                @foreach($categories as $item)
                    @if($main->category->id === $item->id) @continue; @endif
                    <option value="{{ $item->id }}">{{ $item->name.' ('.$item->id.')' }}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label>{{ __('admin.articles-seo') }}</label>
            <select class="form-control" name="seo_id" required>
                <option value="{{ $main->seo->id }}">{{ $main->seo->title.' ('.$main->seo->id.')' }}</option>
                @foreach($seo as $item)
                    @if($main->seo->id === $item->id) @continue; @endif
                    <option value="{{ $item->id }}">{{ $item->title.' ('.$item->id.')' }}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label>{{ __('admin.articles-views') }}</label>
            <input type="text" class="form-control" name="views" value="{{ $main->views }}"
                   placeholder="{{ __('admin.articles-enter-views') }}" required>
        </div>

        <div class="form-group">
            <label>{{ __('admin.articles-slide') }}</label>
            <select class="form-control" name="slide" required>
                @if($main->slide)
                    <option value="1">{{ __('admin.enabled') }}</option>
                    <option value="0">{{ __('admin.disabled') }}</option>
                @else
                    <option value="0">{{ __('admin.disabled') }}</option>
                    <option value="1">{{ __('admin.enabled') }}</option>
                @endif
            </select>
        </div>

        <div class="form-group">
            <label>{{ __('admin.articles-user') }}</label>
            <select class="form-control" name="user_id" required>
                <option value="{{ $main->user->id }}">{{ $main->user->name.' ('.$main->user->id.')' }}</option>
                @foreach($users as $item)
                    @if($main->user->id === $item->id) @continue; @endif
                    <option value="{{ $item->id }}">{{ $item->name.' ('.$item->id.')' }}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label>{{ __('admin.status') }}</label>
            <select class="form-control" name="status" required>
                @if($main->status)
                    <option value="1">{{ __('admin.enabled') }}</option>
                    <option value="0">{{ __('admin.disabled') }}</option>
                @else
                    <option value="0">{{ __('admin.disabled') }}</option>
                    <option value="1">{{ __('admin.enabled') }}</option>
                @endif
            </select>
        </div>

        <button class="btn btn-lg btn-original btn-block" type="submit">{{ __('admin.edit') }}</button>
    </form>
@endsection

resources/views/admin/articles/index.blade.php
@extends('admin.layouts.main')

@section('title',__('admin.articles-title'))

@section('content')
    <div class="row justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <div class="col-lg-9">
            <div class="d-flex">
                <h1 class="h2">@yield('title')</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                </div>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="pull-right">
                <a class="btn btn-original"
                   href="{{ route('articles.create') }}">{{ __('admin.create-articles') }}</a>
            </div>
        </div>
    </div>
    @include('admin.includes.success')
    <div class="table-responsive">
        <table id="datatable" class="table table-striped table-bordered" style="width:100%">
            <thead>
            <tr>
                <th scope="col">{{ __('admin.articles-id') }}</th>
                <th scope="col">{{ __('admin.articles-name') }}</th>
                <th scope="col">{{ __('admin.articles-images') }}</th>
                <th scope="col">{{ __('admin.articles-url') }}</th>
                <th scope="col">{{ __('admin.articles-seo') }}</th>
                <th scope="col">{{ __('admin.articles-category') }}</th>
                <th scope="col">{{ __('admin.articles-views') }}</th>
                <th scope="col">{{ __('admin.status') }}</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            @foreach($main as $item)
                <tr>
                    <th scope="row">{{ $item->id }}</th>
                    <td scope="row">{{ $item->title }}</td>
                    <td scope="row"><img src="{{ asset('storage/'.$item->images) }}" width="100px"></td>
                    <td scope="row">{{ route('site.article.view',$item->url) }}</td>
                    <td scope="row">{{ $item->seo->title.' ('.$item->seo->id.')' }}</td>
                    <td scope="row">{{ $item->category->title.' ('.$item->category->id.')' }}</td>
                    <td scope="row">{{ $item->views }}</td>
                    <td scope="row">
                        @if($item->status)
                            {{ __('admin.enabled') }}
                        @else
                            {{ __('admin.disabled') }}
                        @endif
                    </td>
                    <td scope="row">
                        <a href="{{ route('articles.show',$item->id) }}"><i class="far fa-eye"></i></a>
                        <a href="{{ route('articles.edit',$item->id) }}"><i class="fas fa-edit"></i></a>
                        <form action="{{ route('articles.destroy',$item->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit"><i class="fas fa-trash-alt"></i></button>
                        </form>

                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection

resources/views/admin/articles/show.blade.php
@extends('admin.layouts.main')

@section('title',__('admin.show-articles'))

@section('content')
    @include('admin.includes.title')
    <ul class="nav mb-md-3">
        <li>
            <a href="{{ route('articles.index') }}" class="btn btn-dark">{{ __('admin.back') }}</a>
            <a href="{{ route('articles.edit', $main->id) }}" class="btn btn-primary">{{ __('admin.update') }}</a>
            <form action="{{ route('articles.destroy', $main->id) }}" method="POST">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-danger">{{ __('admin.delete') }}</button>
            </form>
        </li>
    </ul>
    <table class="table">
        <tr>
            <th>{{ __('admin.articles-id') }}</th>
            <td>{{ $main->id }}</td>
        </tr>
        <tr>
            <th>{{ __('admin.articles-name') }}</th>
            <td>{{ $main->title }}</td>
        </tr>
        <tr>
            <th>{{ __('admin.articles-images') }}</th>
            <td><img src="{{ asset('storage/'.$main->images) }}" width="100px" alt=""></td>
        </tr>
        <tr>
            <th>{{ __('admin.articles-url') }}</th>
            <td>{{ route('site.article.view',$main->url) }}</td>
        </tr>
        <tr>
            <th>{{ __('admin.articles-text') }}</th>
            <td>{{ $main->text }}</td>
        </tr>
        <tr>
            <th>{{ __('admin.articles-category') }}</th>
            <td>{{ $main->category->name.' ('.$main->category->id.')' }}</td>
        </tr>
        <tr>
            <th>{{ __('admin.articles-seo') }}</th>
            <td>{{ $main->seo->title.' ('.$main->seo->id.')' }}</td>
        </tr>
        <tr>
            <th>{{ __('admin.articles-views') }}</th>
            <td>{{ $main->views }}</td>
        </tr>
        <tr>
            <th>{{ __('admin.articles-slide') }}</th>
            <td>
                @if($main->slide)
                    {{ __('admin.enabled') }}
                @else
                    {{ __('admin.disabled') }}
                @endif
            </td>
        </tr>
        <tr>
            <th>{{ __('admin.articles-user') }}</th>
            <td>{{ $main->user->name.' ('.$main->seo->id.')' }}</td>
        </tr>
        <tr>
            <th>{{ __('admin.status') }}</th>
            <td>
                @if($main->status)
                    {{ __('admin.enabled') }}
                @else
                    {{ __('admin.disabled') }}
                @endif
            </td>
        </tr>
        <tr>
            <th>{{ __('admin.created') }}</th>
            <td>{{ $main->created_at }}</td>
        </tr>
        <tr>
            <th>{{ __('admin.update') }}</th>
            <td>{{ $main->updated_at }}</td>
        </tr>
    </table>
@endsection